from django.urls import path
from . import views

urlpatterns = [
    path('', views.Home, name='home'),
    path('admin_home', views.Admin_Home, name='admin_home'),
    path('doctor_home', views.Doctor_Home, name='doctor_home'),
    path('patient_home', views.User_Home, name='patient_home'),
    path('about', views.About, name='about'),
    path('contact', views.Contact, name='contact'),
    path('login', views.Login_User, name='login'),
    path('login_admin', views.Login_admin, name='login_admin'),
    path('logout', views.Logout, name='logout'),
    path('change_password', views.Change_Password, name='change_password'),
    path('add_doctor', views.add_doctor, name='add_doctor'),
    path('add_doctor/<int:pid>', views.add_doctor, name='edit_doctor'),
    path('add_heartdetail', views.add_heartdetail, name='add_heartdetail'),
    path('predict_desease/<str:pred>/<str:accuracy>', views.predict_desease, name='predict_desease'),
    path('view_search_pat', views.view_search_pat, name='view_search_pat'),
    path('view_doctor', views.View_Doctor, name='view_doctor'),
    path('view_patient', views.View_Patient, name='view_patient'),
    path('view_feedback', views.View_Feedback, name='view_feedback'),
    path('profile_doctor', views.View_My_Detail, name='profile_doctor'),
    path('edit_doctor/<int:pid>', views.Edit_Doctor, name='edit_doctor'),
    path('edit_profile', views.Edit_My_deatail, name='edit_profile'),
    path('sent_feedback', views.sent_feedback, name='sent_feedback'),
    path('delete_searched/<int:pid>', views.delete_searched, name='delete_searched'),
    path('delete_doctor/<int:pid>', views.delete_doctor, name='delete_doctor'),
    path('delete_feedback/<int:pid>', views.delete_feedback, name='delete_feedback'),
    path('delete_patient/<int:pid>', views.delete_patient, name='delete_patient'),
    path('assign_status/<int:pid>', views.assign_status, name='assign_status'),
    path('view_prediction_history/<int:search_id>', views.view_prediction_history, name='view_prediction_history'),
    path('add_heartdetail_patient/', views.add_heartdetail_patient, name='add_heartdetail_patient'),
] 