# Generated by Django 5.2 on 2025-04-18 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0008_auto_20210821_0121'),
    ]

    operations = [
        migrations.AddField(
            model_name='search_data',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='health.doctor'),
        ),
        migrations.AlterField(
            model_name='search_data',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='health.patient'),
        ),
    ]
