# Generated by Django 5.2 on 2025-06-10 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0011_alter_admin_helath_csv_id_alter_doctor_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionhistory',
            name='feature_impacts',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='search_data',
            name='feature_impacts',
            field=models.TextField(blank=True, null=True),
        ),
    ]
