# Generated by Django 5.2 on 2025-06-10 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0012_predictionhistory_feature_impacts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='user',
        ),
        migrations.AddField(
            model_name='feedback',
            name='email',
            field=models.EmailField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='subject',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
