# Generated by Django 5.2 on 2025-06-10 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0013_remove_feedback_user_feedback_email_feedback_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
