# Generated by Django 5.2 on 2025-06-10 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0014_feedback_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='contact',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
