# Generated by Django 5.2 on 2025-06-10 16:32

import datetime
from django.db import migrations

def convert_date_to_datetime(apps, schema_editor):
    Feedback = apps.get_model('health', 'Feedback')
    for feedback in Feedback.objects.all():
        if isinstance(feedback.date, datetime.date) and not isinstance(feedback.date, datetime.datetime):
            feedback.date = datetime.datetime.combine(feedback.date, datetime.time.min)
            feedback.save()

class Migration(migrations.Migration):

    dependencies = [
        ('health', '0015_feedback_contact'),
    ]

    operations = [
        migrations.RunPython(convert_date_to_datetime),
    ]
