# Generated by Django 5.2 on 2026-06-16 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0017_alter_doctor_user_alter_patient_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='license_document',
            field=models.FileField(blank=True, null=True, upload_to='doctor_licenses/'),
        ),
    ]
